
format = "$os$all"

[aws]
format = ''

[bun]
format = '{[ $symbol ($version) ]($style)} '

[buf]
format = '{[ $symbol ]($style)} '
symbol = " buf"

[c]
symbol = ""

[cmake]
format = '{[ $symbol ($version) ]($style)} '

[cobol]
format = '{[ $symbol ($version) ]($style)} '

[crystal]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[⏱ $duration]($style)"

[daml]
format = '{[ $symbol ($version) ]($style)} '

[dart]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[deno]
format = '{[ $symbol ($version) ]($style)} '

[docker_context]
format = '{[$symbol]($style)} '
symbol = " "

[dotnet]
format = '{[ $symbol ($version) ]($style)} '

[elixir]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[elm]
format = '{[ $symbol ($version) ]($style)} '
symbol = " "

[erlang]
format = '{[ $symbol ($version) ]($style)} '

[fennel]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[fossil_branch]
format = '\[[$symbol$branch]($style)\] '
symbol = " "

[git_branch]
format = '\[[$symbol$branch]($style)\] '
symbol = " "

[git_commit]
tag_symbol = ''

[golang]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[gradle]
format = '{[$symbol]($style)} '
symbol = ""

[guix_shell]
format = '{[$symbol]($style)} '
symbol = ""

[haskell]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[haxe]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[helm]
format = '{[ $symbol ($version) ]($style)} '

[hg_branch]
format = '\[[$symbol$branch]($style)\] '
symbol = " "

[java]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[julia]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[kotlin]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[lua]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[memory_usage]
symbol = "󰍛"

[meson]
format = '{[$symbol]($style)} '
symbol = "󰔷"

[nim]
format = '{[ $symbol ($version) ]($style)} '
symbol = "󰆥"

[nix_shell]
format = '{[$symbol]($style)} '
symbol = ""

[nodejs]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[ocaml]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[opa]
format = '{[ $symbol ($version) ]($style)} '

[openstack]
format = '{[$symbol]($style)} '

[os]
format = '[$symbol]($style)'
disabled = false

[os.symbols]
Alpaquita = "[ ](fg:#FFB86C)"
Alpine = "[ ](fg:#7DD3FC)"
AlmaLinux = "[ ](fg:#CC99FF)"
Amazon = "[ ](fg:#FF9900)"
Android = "[ ](fg:#A4C639)"
Arch = "[ ](fg:#1793D1)"
Artix = "[ ](fg:#B33076)"
CentOS = "[ ](fg:#262577)"
Debian = "[ ](fg:#D70A53)"
DragonFly = "[ ](fg:#9E9E9E)"
Emscripten = "[ ](fg:#FCA121)"
EndeavourOS = "[ ](fg:#6C8DA5)"
Fedora = "[ ](fg:#51A2DA)"
FreeBSD = "[ ](fg:#AB0000)"
Garuda = "[󰛓 ](fg:#B8D899)"
Gentoo = "[ ](fg:#A971B2)"
HardenedBSD = "[󰞌 ](fg:#F5B342)"
Illumos = "[󰈸 ](fg:#F99417)"
Kali = "[ ](fg:#5A9FCF)"
Linux = "[ ](fg:#FCC624)"
Mabox = "[ ](fg:#9ACD32)"
Macos = "[ ](fg:#8E8E8E)"
Manjaro = "[ ](fg:#35BF5C)"
Mariner = "[ ](fg:#0063B1)"
MidnightBSD = "[ ](fg:#ADD8E6)"
Mint = "[ ](fg:#87C095)"
NetBSD = "[ ](fg:#E85858)"
NixOS = "[ ](fg:#5277C3)"
OpenBSD = "[󰈺 ](fg:#FFFF66)"
openSUSE = "[ ](fg:#73BA25)"
OracleLinux = "[󰌷 ](fg:#F80000)"
Pop = "[ ](fg:#37B6E5)"
Raspbian = "[ ](fg:#C70A0A)"
Redhat = "[ ](fg:#CC0000)"
RedHatEnterprise = "[ ](fg:#CC0000)"
RockyLinux = "[ ](fg:#2C5C85)"
Redox = "[󰀘 ](fg:#FFC857)"
Solus = "[󰠳 ](fg:#5294E2)"
SUSE = "[ ](fg:#73BA25)"
Ubuntu = "[ ](fg:#E95420)"
Unknown = "[ ](fg:#808080)"
Void = "[ ](fg:#ACD8D9)"
Windows = "[󰍲 ](fg:#00BCF2)"


[package]
format = '{[ $symbol ($version) ]($style)} '
symbol = "󰏗"

[perl]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[php]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[pijul_channel]
format = '\[[$symbol$branch]($style)\] '
symbol = " "

[python]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[raku]
format = '{[ $symbol ($version) ]($style)} '

[red]
format = '{[ $symbol ($version) ]($style)} '

[rlang]
format = '{[$symbol]($style)} '
symbol =  "󰟔"

[ruby]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[rust]
format = '{[ $symbol ($version) ]($style)} '
symbol = "󱘗"

[scala]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[swift]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""

[solidity]
format = '{[ $symbol ($version) ]($style)} '

[spack]
format = '{[$symbol]($style)} '

[sudo]
format = ''

[terraform]
format = '{[$symbol]($style)} '

[time]
format = ''

[username]
format = ''

[vagrant]
format = '{[ $symbol ($version) ]($style)} '
symbol = "󰔷"

[vlang]
format = '{[ $symbol ($version) ]($style)} '

[zig]
format = '{[ $symbol ($version) ]($style)} '
symbol = ""